version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyDatabase;User Id=sa;Password=YourStrong@Passw0rd;
    depends_on:
      - db
    networks:
      - backend

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y   # ✅ Ensure this line is correctly formatted
      - SA_PASSWORD=YourStrong@Passw0rd
    networks:
      - backend

networks:
  backend:
    driver: bridge
